### Position Create
POST localhost:8080/position/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MTcxNDUxLCJleHAiOjE3NjQyNTc4NTF9.8DrjsGYtSTq5j0q0BTWcyQXA8VVEfgWawIFT_MlpRL4mBQBvZLfHEPNkJsoWmk3EJtowAvISS0KrqKSZcAzB6Q

{
  "name": "Employee"
}

### Position update
PUT localhost:8080/position/update
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MTU4OTMzLCJleHAiOjE3NjQyNDUzMzN9.-CQjFLWEeZmnG8hsPeNxWBmA0EVUnYfGOGOVuAyvRVZVPmbl4sq2hJA1mvBmQSpoZXYRlbMoeciIjg0sojHfdA

{
  "id": 1,
  "name": "Sekritarka"
}

### Position Delete
DELETE localhost:8080/position/delete
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MTU4OTMzLCJleHAiOjE3NjQyNDUzMzN9.-CQjFLWEeZmnG8hsPeNxWBmA0EVUnYfGOGOVuAyvRVZVPmbl4sq2hJA1mvBmQSpoZXYRlbMoeciIjg0sojHfdA
Content-Type:  application/json

{
  "id": 1
}

### Position subscribe
POST localhost:8080/position/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MTYxOTE5LCJleHAiOjE3NjQyNDgzMTl9.OPQrebLPHJ9JYTNbqUSeo1gbiZcBLAPHv6A_MWuWyEPOlX4Pfnn3VPqhQ3K11d2D1_GXda9MxAAkx19PThrC_g

{
  "profileId": 10,
  "positionId": 3
}