### Profile Create
POST localhost:8080/profile/admin/create
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MTcyNTE3LCJleHAiOjE3NjQyNTg5MTd9.RQwlSw75lM66VtJWrFH5mrMYIlGqUwaT_qEjdq-SO9lzNgakkJpJxNYo8u7dO_jLaA_b-MkdL4lWcDgdItwOIA

{ "name": "Toshmat",
  "surname": "Toshmatov",
  "username": "Toshmat002",
  "password": "12345678"
}

### Profile get List
GET localhost:8080/profile/admin/get/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MjQwOTk4LCJleHAiOjE3NjQzMjczOTh9.7DPZEqSC1yP9nVNyoHFxW-6Qeu85wt71_q2BTXhBBpqqFA-g6D5mtOpq2tAE7UT-nH0VpIMNi0bWLDWr04ivHw

### Profile update detail
PUT localhost:8080/profile/user/update/detail
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJrYXIwMDIiLCJzdWIiOiJrYXIwMDIiLCJpYXQiOjE3NjQwODcwNjYsImV4cCI6MTc2NDE3MzQ2Nn0.tKRbt1SB3O77WEnjtrnWq2UI8yfkc_xYdNSiWzc6SH8k0C1D2Dv5Z4mP6MUy6FL2X4vw0m_46HSabTZXnX0r6A

{ "name": "Karima",
  "surname": "Karimova"
}

### Profile update username
PUT localhost:8080/profile/user/update/username?username=karima002
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJrYXIwMDIiLCJzdWIiOiJrYXIwMDIiLCJpYXQiOjE3NjQwODg0MDQsImV4cCI6MTc2NDE3NDgwNH0.44s2oEWyzRNVOFEBuBmHBNV9xJh4Gmv7UgmCH14gld8LH_kHAlbBvflXu4aaijC54v-kkYxxejYv4R2sX4sZfQ

### Profile update password
PUT localhost:8080/profile/user/update/password?password=12345678
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJWYWxpMDAyIiwic3ViIjoiVmFsaTAwMiIsImlhdCI6MTc2NDIzOTA5MiwiZXhwIjoxNzY0MzI1NDkyfQ.s2rmlC7x1-ulPxowCXeQYPGgK0LZxQ9RX8GDsQm_pD87BtEn3sm5VOPSaECUBYyi0OSv9fBUKcN0w-ZX35yqHg

### Profile get datail
GET localhost:8080/profile/user/get/detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJWYWwwMDEiLCJzdWIiOiJWYWwwMDEiLCJpYXQiOjE3NjQwOTQ1MzAsImV4cCI6MTc2NDE4MDkzMH0.uc1TdjP7Y-qCHhxPeCvX40lFAS09D8NIVFghqn7LhCKVInaXbPTBbNsqpAPNO84ufkdE5qewPl1JAErBe7ZCyQ

### Profile Delete
DELETE localhost:8080/profile/delete
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJrYXIwMDciLCJzdWIiOiJrYXIwMDciLCJpYXQiOjE3NjQwOTI3MzUsImV4cCI6MTc2NDE3OTEzNX0.u54vYUGRcNNDAuSgY6IgdTDMScAWdIbVQk1WKXXxDeb5sDCqGtDDJe6QHFQmT8Q7EwANa_1moMILT3-qAHYcdA

### Profile Pagination
GET http://localhost:8080/profile/admin/pagination?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MTcyNjA3LCJleHAiOjE3NjQyNTkwMDd9.bMuWLt4pBz9Tn55Z681xT-nOooTcvrFLGIXC544VeGrJGOSy0aE8R_phCYQSK4Li26A7ZWickpdkjDPDPSNwsA

### Profile Filter
POST http://localhost:8080/profile/admin/filter?page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MTc4OTkxLCJleHAiOjE3NjQyNjUzOTF9.lCE4R7vTSwLZR3wA9d-OWDrjnyCmc06ZEBHNXjbH1ywgmY7sMlxWBMmywSSMaqfKPDNcGaIYd0Mak2sOr54s6A

{
  "position": "Menejer",
  "branch": "O'rta Bo'lim"
}