### TOKEN
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzE1MzM5LCJleHAiOjE3NjQ0MDE3Mzl9.rx4Q0tNNSfWojP8d64a6hHdGiW8f0VnWXVq8zghxbXFrLfVry6Qop5MwSHUfHiTs8GdjfqbVTmuSjUjrtL3j8g

###Create Schedule
POST http://localhost:8080/work-time/admin/create/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzE5Nzc5LCJleHAiOjE3NjQ0MDYxNzl9.DeuwRt44_r61RQJB3zczpnCHqjYLv2OQZC2kKf0Z-QDkRjxP0tMrII6CIbdmXlrrtcq7ZpOIAFnnjGpI0NJkyw
Content-Type: application/json

{
  "profileId": 6,
  "inputTime": "2025-02-01T10:00:00",
  "outputTime": "2025-02-01T19:00:00"
}

###Get All Schedules
GET http://localhost:8080/work-time/admin/get/all/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzE2OTA5LCJleHAiOjE3NjQ0MDMzMDl9.08aTkieR0gZUeDfPjY7U0TfN9dQm8y3z3fZJPYlbT_lL3X7HjK1Ddpe164GUsoCAq2MImWSsqjo04G7iuAiNsw



### Update Schedule //todo
PUT http://localhost:8080/work-time/admin/update/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzE2MDc5LCJleHAiOjE3NjQ0MDI0Nzl9.R-WmWcxTBzfyJ6ZImdM3vz8bJTO79ogf_jGmH-sr4gxQBP02mQ5APBUqf6roR6fn4ZOxaLmHuXlvUUDBT30cDw
Content-Type: application/json

{
  "profileId": 2,
  "startTime": "2025-02-01T09:00:00",
  "endTime": "2025-02-01T18:00:00"
}



### Delete Schedule
DELETE http://localhost:8080/work-time/admin/delete/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzE2OTA5LCJleHAiOjE3NjQ0MDMzMDl9.08aTkieR0gZUeDfPjY7U0TfN9dQm8y3z3fZJPYlbT_lL3X7HjK1Ddpe164GUsoCAq2MImWSsqjo04G7iuAiNsw
Content-Type: application/json

{
  "id": 1
}



### Get All Disruptions
GET http://localhost:8080/work-time/admin/get/all/disruption
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIwMDY0LCJleHAiOjE3NjQ0MDY0NjR9.n288rxkwxSJsMGPWvtdXZ_kjCMe3gG7XNHtcNS33vXhQCreuUskvnENfy18UP1yeThgY8TjbIBlkqARUWcELbA



### Get All History
GET http://localhost:8080/work-time/admin/get/all/history
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIwMDY0LCJleHAiOjE3NjQ0MDY0NjR9.n288rxkwxSJsMGPWvtdXZ_kjCMe3gG7XNHtcNS33vXhQCreuUskvnENfy18UP1yeThgY8TjbIBlkqARUWcELbA



### Get Week History
GET http://localhost:8080/work-time/admin/get/week/history?startDate=2025-02-01T00:00:00&endDate=2025-02-07T23:59:59
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIwMDY0LCJleHAiOjE3NjQ0MDY0NjR9.n288rxkwxSJsMGPWvtdXZ_kjCMe3gG7XNHtcNS33vXhQCreuUskvnENfy18UP1yeThgY8TjbIBlkqARUWcELbA



### Get Month History
GET http://localhost:8080/work-time/admin/get/month/history?year=2025&month=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIwMDY0LCJleHAiOjE3NjQ0MDY0NjR9.n288rxkwxSJsMGPWvtdXZ_kjCMe3gG7XNHtcNS33vXhQCreuUskvnENfy18UP1yeThgY8TjbIBlkqARUWcELbA



### Profile Work Time
PUT http://localhost:8080/work-time/user/worktime
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJUb3NoMDAyIiwic3ViIjoiVG9zaDAwMiIsImlhdCI6MTc2NDMyMDAwMCwiZXhwIjoxNzY0NDA2NDAwfQ.cUgY3BIwUoe4KSNqbtVvBYl1jcW_jr2FOHSAYmJj7LXw3QxdYMFCholi67mBSGva1twSz2h-w5qeiPVOlsbHMw