###Create Schedule
POST http://localhost:8080/work-time/admin/create/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIyODIyLCJleHAiOjE3NjQ0MDkyMjJ9.J6n0NXGiEq0VSCCfOvFKoOsfZE_GiZ_CJYjT4oSl8edUBe4IU-tpx1sRTJeVeR385zXTWgcPknVfHvoI_llg9A
Content-Type: application/json

{
  "profileId": 7,
  "inputTime": "2025-02-01T10:00:00",
  "outputTime": "2025-02-01T19:00:00"
}

###Get All Schedules
GET http://localhost:8080/work-time/admin/get/all/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzE2OTA5LCJleHAiOjE3NjQ0MDMzMDl9.08aTkieR0gZUeDfPjY7U0TfN9dQm8y3z3fZJPYlbT_lL3X7HjK1Ddpe164GUsoCAq2MImWSsqjo04G7iuAiNsw



### Update Schedule
PUT http://localhost:8080/work-time/admin/update/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIzMDkxLCJleHAiOjE3NjQ0MDk0OTF9._fgSnQc-YsVkYR6EnxEAA-lXJIhv3L5oarceVvf4QrY7pg_gUdEqag14Px8tPyj0JAfgZG2SugGQ78xRyqyH9Q
Content-Type: application/json

{
  "profileId": 7,
  "inputTime": "2025-02-01T09:00:00",
  "outputTime": "2025-02-01T18:00:00"
}



### Delete Schedule
DELETE http://localhost:8080/work-time/admin/delete/schedule
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzE2OTA5LCJleHAiOjE3NjQ0MDMzMDl9.08aTkieR0gZUeDfPjY7U0TfN9dQm8y3z3fZJPYlbT_lL3X7HjK1Ddpe164GUsoCAq2MImWSsqjo04G7iuAiNsw
Content-Type: application/json

{
  "id": 1
}



### Get All Disruptions
GET http://localhost:8080/work-time/admin/get/all/disruption
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIwMDY0LCJleHAiOjE3NjQ0MDY0NjR9.n288rxkwxSJsMGPWvtdXZ_kjCMe3gG7XNHtcNS33vXhQCreuUskvnENfy18UP1yeThgY8TjbIBlkqARUWcELbA



### Get All History
GET http://localhost:8080/work-time/admin/get/all/history
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzIwMDY0LCJleHAiOjE3NjQ0MDY0NjR9.n288rxkwxSJsMGPWvtdXZ_kjCMe3gG7XNHtcNS33vXhQCreuUskvnENfy18UP1yeThgY8TjbIBlkqARUWcELbA



### Get interval History
GET http://localhost:8080/work-time/admin/get/interval/history
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiQWxpMDAxIiwic3ViIjoiQWxpMDAxIiwiaWF0IjoxNzY0MzI0MDE4LCJleHAiOjE3NjQ0MTA0MTh9.Fy4OJPZrlamBDKSE3pJPBfuIyEla7IB6QcaXq-zyPHKabfzShM4tGKw8h3TbMtjs4F-Y8w_39ILSO5ktqq-sYA
Content-Type: application/json

{
  "startDate": "2025-02-01T09:00:00",
  "endDate": "2025-12-01T18:00:00"
}

### Profile Work Time
PUT http://localhost:8080/work-time/user/worktime
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJUb3NoMDAzIiwic3ViIjoiVG9zaDAwMyIsImlhdCI6MTc2NDMyMjg5NywiZXhwIjoxNzY0NDA5Mjk3fQ.VzAoRy2B9MAbwESEmhfHDLY1nEgd0w2DpmbY11CXZmtm6oGoxiRbQ4BKAf3XI2K_zqqugUw4zobRVmYgKKxSbw